# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9c64a380da382ac318c3339983191c3d6b148f4e3e581671340725419be19fa4c858d84d93e86d42e55947c990852af513b49436560a9f81ccc4590a68090bd

test:
  secret_key_base: 547f49c4ad74fffc40b9abe58a1d835372d86d20f5130c545c9063245f6859cff706ad209f57f12cad8ea4cc62207479442224459c47765fa673c034569b5741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
